#ifndef ENGINE_INCLUDE_ENJAM_VULKAN_DEFINES_H_
#define ENGINE_INCLUDE_ENJAM_VULKAN_DEFINES_H_

#define VK_ENABLE_BETA_EXTENSIONS

#define ENJAM_VULKAN_VALIDATION    0x00000001
#define ENJAM_VULKAN_DEBUG_UTILS   0x00000002

#define ENJAM_VULKAN_FLAGS (ENJAM_VULKAN_VALIDATION | ENJAM_VULKAN_DEBUG_UTILS)

#define ENJAM_VULKAN_ENABLED(flags) (((ENJAM_VULKAN_FLAGS) & (flags)) == (flags))

#endif //ENGINE_INCLUDE_ENJAM_VULKAN_DEFINES_H_
